name: Latest Twitter Tweets
on:
  schedule:
    - cron: '0 0 1-31/3 * *' # Every 3rd day of the month at 12:00AM UTC
  workflow_dispatch:

jobs:
  update-readme-with-twitter:
    name: Update this repo's README with the latest tweets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "TWITTER"
          feed_list: "https://nitter.net/search/rss?f=tweets&q=montasimmamun, https://nitter.net/search?f=tweets&q=montasimmamun"
          commit_message: "Updated with the latest tweets"
          committer_email: "montasimmamun@gmail.com"
